### ISSUE TITLE
Support stackdriver output plugin

### ISSUE THREAD

**Issue by niedbalski** [calyptia/fluent-bit-ci#8]
* Add a simple integration testing that supports Google Stackdriver output plugin [0]
* Validate that input -> output pipeline works.

[0] https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver

**Comment by pwhelan** [comment]
Still waiting on access to the Google Cloud dashboard, at least to the loggin area.

![image](https://user-images.githubusercontent.com/601645/124019419-0b7e4800-d9b7-11eb-87b0-0ba5607afd51.png)

**Comment by pwhelan** [comment]
Here is an example client in go thatr can list log entries so we can verify log entries are being written to stackdriver: https://github.com/GoogleCloudPlatform/golang-samples/blob/HEAD/logging/simplelog/simplelog.go.

**Comment by pwhelan** [comment]
I now have access and have a WIP branch.

**Comment by niedbalski** [comment]
This has been fixed on #12
